language: node_js
node_js: 
    - 12.17.0
cache: npm

install:
    - npm install
before_script:
    - npm install -g angular-cli-ghpages    
script:
    - ng build --base-href https://JulianCuestas.github.io/HeroMarvel/


