language: node_js
branches:
    only:
        - master
        - gh-pages
notifications:
    email:
      recipients:
        - julian.dcj06@gmail.com
node_js: 
    - 12.17.0
cache: npm

install:
    - npm install
before_script:
    - npm install -g angular-cli-ghpages    
script:
    - ng build --base-href https://JulianCuestas.github.io/HeroMarvel/
    - ngh --no-silent


